os: linux
services:
  - docker
  
script:
  - cd app
  - docker-compose -f prod-docker-compose.yml up -d
  - cd ../test
  - docker build --tag api-test .
  - docker run --network host api-test
  
after_success:
  - docker login --username ${D_USER} --password ${D_PASSWORD}
  - cd app
  - docker-compose push
