os: linux
services:
  - docker
  
script:
  - cd app
  - echo "WEBHOOK_URL=$TWEBHOOK_URL" >> web.env
  - docker-compose -d up
  - cd ../test
  - docker build --tag api-test .
  - docker run --network host api-test
  
